name: "💪 Enhancement Request"
description: Create a new issue for a new enhancement request
title: "💪 <title>"
labels: ["enhancement"]
body:
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: Start of development
      placeholder: "year/month/day"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Provide a brief explanation of the enhancement
      placeholder: Describe in a few lines your enhancement request
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: How it is critical this bug?
      multiple: true
      options:
        - 🔴 Critical
        - 🟠 High
        - 🟡 Medium
        - 🟢 Low
  - type: input
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: Pull request used
      placeholder: "#Pull Request ID"
    validations:
      required: false
  - type: input
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: Common issues
      placeholder: "#Issues IDs"
    validations:
      required: false
  - type: textarea
    id: reference
    attributes:
      label: "Reference"
      description: Please indicate the portion of code to improve (using code permalink for example)
      placeholder: A reference to the partion of code involved in this enhancement
      render: bash
    validations:
      required: false
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of your feature
      placeholder: Soem basic example useful to describe the expected behaviour
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "Drawbacks"
      description: What are the drawbacks/impacts of your feature request?
      placeholder: Identify the drawbacks and impacts while being neutral on your feature request
    validations:
      required: true
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved?
      placeholder: Identify any unresolved issues
    validations:
      required: false
